// Copyright (c) 2026 Trovalo. All rights reserved. Unauthorized use prohibited.
// Configurazione centri commerciali
const MALLS_CONFIG = [
    {
        id: 'porta_di_roma',
        name: 'Porta di Roma',
        location: 'Roma, Italia',
        description: 'Il più grande centro commerciale di Roma',
        floors: 2,
        escalators: 4,
        totalShops: 199,
        logo: '<img src="PortaDiRomaIcona.png" alt="Porta di Roma" >'
    },
    {
        id: 'granroma',
        name: 'GranRoma',
        location: 'Roma, Italia',
        description: 'Centro commerciale nella zona Est di Roma',
        floors: 2,
        escalators: 2,
        totalShops: 93,
        logo: '<img src="GranRomaIcona.jpg" alt="GranRoma" >'
    },
    {
        id: 'altro_mall',
        name: 'Altri Centri Commerciali',
        location: 'In arrivo...',
        description: 'Presto disponibili altri centri',
        floors: 0,
        escalators: 0,
        totalShops: 0,
        logo: '🏢',
        comingSoon: true
    }
];

// Dati negozi per centro commerciale
const MALLS_DATA = {
    'porta_di_roma': [
    // Piano 0 - Anello Esterno (42 negozi)
    { id: 'p0_outer_1', name: 'Nitò', floor: 0, zone: 'OUTER', position: 1, type: 'Food e Ristoranti' },
    { id: 'p0_outer_2', name: 'Capatoast', floor: 0, zone: 'OUTER', position: 2, type: 'Food e Ristoranti' },
    { id: 'p0_outer_3', name: 'Salmoiraghi & Viganò', floor: 0, zone: 'OUTER', position: 3, type: 'Salute e Bellezza' },
    { id: 'p0_outer_4', name: 'MAC', floor: 0, zone: 'OUTER', position: 4, type: 'Salute e Bellezza' },
    { id: 'p0_outer_5', name: 'MiRaggi', floor: 0, zone: 'OUTER', position: 5, type: 'Moda' },
    { id: 'p0_outer_6', name: 'Pull&Bear', floor: 0, zone: 'OUTER', position: 6, type: 'Moda' },
    { id: 'p0_outer_7', name: 'AppleStore', floor: 0, zone: 'OUTER', position: 7, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p0_outer_8', name: 'Alcott', floor: 0, zone: 'OUTER', position: 8, type: 'Moda' },
    { id: 'p0_outer_9', name: 'Bershka', floor: 0, zone: 'OUTER', position: 9, type: 'Moda' },
    { id: 'p0_outer_10', name: 'JD', floor: 0, zone: 'OUTER', position: 10, type: 'Moda' },
    { id: 'p0_outer_wc_1', name: 'Bagno Sud P0', floor: 0, zone: 'OUTER', position: 11, type: 'Bagni' },
    { id: 'p0_outer_11', name: 'Starbucks', floor: 0, zone: 'OUTER', position: 12, type: 'Food e Ristoranti' },
    { id: 'p0_outer_12', name: 'Burger King', floor: 0, zone: 'OUTER', position: 13, type: 'Food e Ristoranti' },
    { id: 'p0_outer_13', name: 'Conad', floor: 0, zone: 'OUTER', position: 14, type: 'Supermercati' },
    { id: 'p0_outer_14', name: 'La Feltrinelli', floor: 0, zone: 'OUTER', position: 15, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p0_outer_15', name: 'Farinella', floor: 0, zone: 'OUTER', position: 16, type: 'Food e Ristoranti' },
    { id: 'p0_outer_16', name: 'Juneco', floor: 0, zone: 'OUTER', position: 17, type: 'Salute e Bellezza' },
    { id: 'p0_outer_17', name: 'Poste Italiane', floor: 0, zone: 'OUTER', position: 18, type: 'Servizi' },
    { id: 'p0_outer_18', name: 'Jean Louis David', floor: 0, zone: 'OUTER', position: 19, type: 'Salute e Bellezza' },
    { id: 'p0_outer_19', name: 'È qui Parafarmacia', floor: 0, zone: 'OUTER', position: 20, type: 'Salute e Bellezza' },
    { id: 'p0_outer_20', name: 'Chic Accent Samsonite Group', floor: 0, zone: 'OUTER', position: 21, type: 'Moda' },
    { id: 'p0_outer_21', name: '1A Clean Lavasecco', floor: 0, zone: 'OUTER', position: 22, type: 'Servizi' },
    { id: 'p0_outer_22', name: 'Bialetti', floor: 0, zone: 'OUTER', position: 23, type: 'Prodotti per la casa' },
    { id: 'p0_outer_23', name: 'Pasticceria Bellavia', floor: 0, zone: 'OUTER', position: 24, type: 'Food e Ristoranti' },
    { id: 'p0_outer_24', name: 'Flying Tiger', floor: 0, zone: 'OUTER', position: 25, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p0_outer_25', name: 'Mediaworld', floor: 0, zone: 'OUTER', position: 26, type: 'Cultura, Regali, Tempo Libero' },
    //{ id: 'p0_outer_26', name: 'Just Design', floor: 0, zone: 'OUTER', position: 26 },
    { id: 'p0_outer_27', name: 'Normal', floor: 0, zone: 'OUTER', position: 28, type: 'Salute e Bellezza' },
    { id: 'p0_outer_28', name: 'Snipes', floor: 0, zone: 'OUTER', position: 29, type: 'Moda' },
    { id: 'p0_outer_29', name: 'Barca', floor: 0, zone: 'OUTER', position: 30, type: 'Moda' },
    { id: 'p0_outer_30', name: 'Rituals', floor: 0, zone: 'OUTER', position: 31, type: 'Salute e Bellezza' },
    { id: 'p0_outer_31', name: 'United Colors of Benetton', floor: 0, zone: 'OUTER', position: 32, type: 'Moda' },
    { id: 'p0_outer_32', name: 'Dr. Martens', floor: 0, zone: 'OUTER', position: 33, type: 'Moda' },
    { id: 'p0_outer_33', name: 'H&M', floor: 0, zone: 'OUTER', position: 34, type: 'Moda' },
    { id: 'p0_outer_34', name: 'Just Design', floor: 0, zone: 'OUTER', position: 35, type: 'Moda' },
    { id: 'p0_outer_35', name: 'Lego', floor: 0, zone: 'OUTER', position: 36, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p0_outer_36', name: 'Tezenis', floor: 0, zone: 'OUTER', position: 37, type: 'Moda' },
    { id: 'p0_outer_37', name: "Levi's", floor: 0, zone: 'OUTER', position: 38, type: 'Moda' },
    { id: 'p0_outer_wc_2', name: 'Bagno Nord P0', floor: 0, zone: 'OUTER', position: 39, type: 'Bagni' },
    { id: 'p0_outer_38', name: "Pop Mart", floor: 0, zone: 'OUTER', position: 40, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p0_outer_39', name: 'Suite Benedict', floor: 0, zone: 'OUTER', position: 41, type: 'Moda' },
    { id: 'p0_outer_40', name: 'Decathlon', floor: 0, zone: 'OUTER', position: 42, type: 'Cultura, Regali, Tempo Libero' },

    // Piano 0 - Isola SX (36 negozi)
    { id: 'p0_isl_sx_1', name: 'Piquadro', floor: 0, zone: 'ISLAND_SX', position: 1, type: 'Moda' },
    { id: 'p0_isl_sx_2', name: 'GIOVANNI RASPINI', floor: 0, zone: 'ISLAND_SX', position: 2, type: 'Moda' },
    { id: 'p0_isl_sx_3', name: 'Nyx Professional Makeup', floor: 0, zone: 'ISLAND_SX', position: 3, type: 'Salute e Bellezza' },
    { id: 'p0_isl_sx_4', name: 'Liu-Jo', floor: 0, zone: 'ISLAND_SX', position: 4, type: 'Moda' },
    { id: 'p0_isl_sx_5', name: 'Motivi', floor: 0, zone: 'ISLAND_SX', position: 5, type: 'Moda' },
    { id: 'p0_isl_sx_6', name: 'Clayton', floor: 0, zone: 'ISLAND_SX', position: 6, type: 'Moda' },
    { id: 'p0_isl_sx_7', name: 'Bata', floor: 0, zone: 'ISLAND_SX', position: 7, type: 'Moda' },
    { id: 'p0_isl_sx_8', name: 'Nuna Lie', floor: 0, zone: 'ISLAND_SX', position: 8, type: 'Moda' },
    { id: 'p0_isl_sx_9', name: 'Okaidi', floor: 0, zone: 'ISLAND_SX', position: 9, type: 'Moda' },
    { id: 'p0_isl_sx_10', name: 'Vicolo', floor: 0, zone: 'ISLAND_SX', position: 10, type: 'Moda' },
    { id: 'p0_isl_sx_11', name: 'Bottega Verde', floor: 0, zone: 'ISLAND_SX', position: 11, type: 'Salute e Bellezza' },
    { id: 'p0_isl_sx_12', name: "Claire's", floor: 0, zone: 'ISLAND_SX', position: 12, type: 'Moda' },
    { id: 'p0_isl_sx_13', name: 'Goldenpoint', floor: 0, zone: 'ISLAND_SX', position: 13, type: 'Moda' },
    { id: 'p0_isl_sx_14', name: 'Thun', floor: 0, zone: 'ISLAND_SX', position: 14, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p0_isl_sx_15', name: 'La Casa de las Carcasas', floor: 0, zone: 'ISLAND_SX', position: 15, type: 'Moda' },
    { id: 'p0_isl_sx_16', name: 'Centri Unico', floor: 0, zone: 'ISLAND_SX', position: 16, type: 'Salute e Bellezza' },
    { id: 'p0_isl_sx_17', name: 'Via Condotti', floor: 0, zone: 'ISLAND_SX', position: 17, type: 'Moda' },
    { id: 'p0_isl_sx_18', name: 'Solo Tempo', floor: 0, zone: 'ISLAND_SX', position: 18, type: 'Moda' },
    { id: 'p0_isl_sx_19', name: 'Windtre', floor: 0, zone: 'ISLAND_SX', position: 19, type: 'Servizi' },
    { id: 'p0_isl_sx_20', name: '7 Camicie', floor: 0, zone: 'ISLAND_SX', position: 20, type: 'Moda' },
    { id: 'p0_isl_sx_21', name: 'Yves Rocher', floor: 0, zone: 'ISLAND_SX', position: 21, type: 'Salute e Bellezza' },
    { id: 'p0_isl_sx_22', name: 'Calzedonia', floor: 0, zone: 'ISLAND_SX', position: 22, type: 'Moda' },
    { id: 'p0_isl_sx_23', name: 'Intimissimi', floor: 0, zone: 'ISLAND_SX', position: 23, type: 'Moda' },
    { id: 'p0_isl_sx_24', name: 'KIKO Milano', floor: 0, zone: 'ISLAND_SX', position: 24, type: 'Salute e Bellezza' },
    { id: 'p0_isl_sx_25', name: 'Douglas Ovest', floor: 0, zone: 'ISLAND_SX', position: 25, type: 'Salute e Bellezza' },
    { id: 'p0_isl_sx_26', name: 'Sandro Ferrone', floor: 0, zone: 'ISLAND_SX', position: 26, type: 'Moda' },
    { id: 'p0_isl_sx_27', name: 'Zuiki', floor: 0, zone: 'ISLAND_SX', position: 27, type: 'Moda' },
    { id: 'p0_isl_sx_28', name: 'Nuvolari', floor: 0, zone: 'ISLAND_SX', position: 28, type: 'Moda' },
    { id: 'p0_isl_sx_29', name: 'Yamamay uomo', floor: 0, zone: 'ISLAND_SX', position: 29, type: 'Moda' },
    { id: 'p0_isl_sx_30', name: 'Yamamay', floor: 0, zone: 'ISLAND_SX', position: 30, type: 'Moda' },
    { id: 'p0_isl_sx_31', name: 'Original Marines', floor: 0, zone: 'ISLAND_SX', position: 31, type: 'Moda' },
    { id: 'p0_isl_sx_32', name: 'Parfois', floor: 0, zone: 'ISLAND_SX', position: 32, type: 'Moda' },
    { id: 'p0_isl_sx_33', name: 'Lovable', floor: 0, zone: 'ISLAND_SX', position: 33, type: 'Moda' },
    { id: 'p0_isl_sx_34', name: 'Bluespirit', floor: 0, zone: 'ISLAND_SX', position: 34, type: 'Moda' },
    { id: 'p0_isl_sx_35', name: 'Fielmann', floor: 0, zone: 'ISLAND_SX', position: 35, type: 'Salute e Bellezza' },
    { id: 'p0_isl_sx_36', name: 'Vestopazzo', floor: 0, zone: 'ISLAND_SX', position: 36, type: 'Moda' },

    // Piano 0 - Isola DX (32 negozi)
    { id: 'p0_isl_dx_1', name: 'illy Caffè', floor: 0, zone: 'ISLAND_DX', position: 1, type: 'Food e Ristoranti' },
    { id: 'p0_isl_dx_2', name: 'Bijou Brigitte', floor: 0, zone: 'ISLAND_DX', position: 2, type: 'Moda' },
    { id: 'p0_isl_dx_3', name: 'Nashi', floor: 0, zone: 'ISLAND_DX', position: 3, type: 'Salute e Bellezza' },
    { id: 'p0_isl_dx_4', name: 'Pandora', floor: 0, zone: 'ISLAND_DX', position: 4, type: 'Moda' },
    { id: 'p0_isl_dx_5', name: 'Swarovski', floor: 0, zone: 'ISLAND_DX', position: 5, type: 'Moda' },
    { id: 'p0_isl_dx_6', name: 'Nespresso', floor: 0, zone: 'ISLAND_DX', position: 6, type: 'Prodotti per la casa' },
    { id: 'p0_isl_dx_7', name: 'Swatch', floor: 0, zone: 'ISLAND_DX', position: 7, type: 'Moda' },
    { id: 'p0_isl_dx_8', name: 'Raggi', floor: 0, zone: 'ISLAND_DX', position: 8, type: 'Moda' },
    { id: 'p0_isl_dx_9', name: 'Machapokè', floor: 0, zone: 'ISLAND_DX', position: 9, type: 'Food e Ristoranti' },
    { id: 'p0_isl_dx_10', name: 'Heikos', floor: 0, zone: 'ISLAND_DX', position: 10, type: 'Prodotti per la casa' },
    { id: 'p0_isl_dx_11', name: 'Re Sole', floor: 0, zone: 'ISLAND_DX', position: 11, type: 'Salute e Bellezza' },
    { id: 'p0_isl_dx_12', name: 'Medi Market', floor: 0, zone: 'ISLAND_DX', position: 12, type: 'Salute e Bellezza' },
    { id: 'p0_isl_dx_13', name: 'Kasanova', floor: 0, zone: 'ISLAND_DX', position: 13, type: 'Prodotti per la casa' },
    { id: 'p0_isl_dx_14', name: 'Talco', floor: 0, zone: 'ISLAND_DX', position: 14, type: 'Moda' },
    { id: 'p0_isl_dx_15', name: 'Douglas Est', floor: 0, zone: 'ISLAND_DX', position: 15, type: 'Salute e Bellezza' },
    { id: 'p0_isl_dx_16', name: 'La Casa del Tabacco', floor: 0, zone: 'ISLAND_DX', position: 16, type: 'Servizi' },
    { id: 'p0_isl_dx_17', name: 'Marlù', floor: 0, zone: 'ISLAND_DX', position: 17, type: 'Moda' },
    { id: 'p0_isl_dx_18', name: 'Primadonna Collection', floor: 0, zone: 'ISLAND_DX', position: 18, type: 'Moda' },
    { id: 'p0_isl_dx_19', name: 'Vodafone', floor: 0, zone: 'ISLAND_DX', position: 19, type: 'Servizi' },
    { id: 'p0_isl_dx_20', name: 'Gamelife', floor: 0, zone: 'ISLAND_DX', position: 20, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p0_isl_dx_21', name: 'Doppelganger piano 0', floor: 0, zone: 'ISLAND_DX', position: 21, type: 'Moda' },
    { id: 'p0_isl_dx_22', name: 'TIM Gruppo Distribuzione Spa (piano 0)', floor: 0, zone: 'ISLAND_DX', position: 22, type: 'Servizi' },
    { id: 'p0_isl_dx_23', name: 'Iliad', floor: 0, zone: 'ISLAND_DX', position: 23, type: 'Servizi' },
    { id: 'p0_isl_dx_24', name: 'Capello point', floor: 0, zone: 'ISLAND_DX', position: 24, type: 'Servizi' },
    { id: 'p0_isl_dx_25', name: "D'Amante", floor: 0, zone: 'ISLAND_DX', position: 25, type: 'Moda' },
    { id: 'p0_isl_dx_26', name: 'IUMAN-Intimissimi Uomo', floor: 0, zone: 'ISLAND_DX', position: 26, type: 'Moda' },
    { id: 'p0_isl_dx_27', name: 'Lush', floor: 0, zone: 'ISLAND_DX', position: 27, type: 'Salute e Bellezza' },
    { id: 'p0_isl_dx_28', name: 'GrandVision by Avanzi', floor: 0, zone: 'ISLAND_DX', position: 28, type: 'Salute e Bellezza' },
    { id: 'p0_isl_dx_29', name: 'Miriade', floor: 0, zone: 'ISLAND_DX', position: 29, type: 'Moda' },
    { id: 'p0_isl_dx_30', name: 'Carpisa', floor: 0, zone: 'ISLAND_DX', position: 30, type: 'Moda' },
    { id: 'p0_isl_dx_31', name: 'Artigli', floor: 0, zone: 'ISLAND_DX', position: 31, type: 'Moda' },
    { id: 'p0_isl_dx_32', name: 'O Mai', floor: 0, zone: 'ISLAND_DX', position: 32, type: 'Moda' },

    // Piano 1 - Anello Esterno (48 negozi)  
    { id: 'p1_outer_1', name: 'Mò Café', floor: 1, zone: 'OUTER', position: 1, type: 'Food e Ristoranti' },
    { id: 'p1_outer_2', name: 'Numero Uno', floor: 1, zone: 'OUTER', position: 2, type: 'Food e Ristoranti' },
    { id: 'p1_outer_3', name: 'Fratelli la bufala', floor: 1, zone: 'OUTER', position: 3, type: 'Food e Ristoranti' },
    { id: 'p1_outer_4', name: 'Poke House', floor: 1, zone: 'OUTER', position: 4, type: 'Food e Ristoranti' },
    { id: 'p1_outer_5', name: 'Kebhouze', floor: 1, zone: 'OUTER', position: 5, type: 'Food e Ristoranti' },
    { id: 'p1_outer_6', name: 'Milos Greek Food', floor: 1, zone: 'OUTER', position: 6, type: 'Food e Ristoranti' },
    { id: 'p1_outer_7', name: 'Toast House', floor: 1, zone: 'OUTER', position: 7, type: 'Food e Ristoranti' },
    { id: 'p1_outer_8', name: 'Menodiciotto', floor: 1, zone: 'OUTER', position: 8, type: 'Food e Ristoranti' },
    { id: 'p1_outer_9', name: "McDonald's", floor: 1, zone: 'OUTER', position: 9, type: 'Food e Ristoranti' },
    { id: 'p1_outer_10', name: 'Dispensa Emilia', floor: 1, zone: 'OUTER', position: 10, type: 'Food e Ristoranti' },
    { id: 'p1_outer_11', name: 'Flunch', floor: 1, zone: 'OUTER', position: 11, type: 'Food e Ristoranti' },
    { id: 'p1_outer_12', name: 'Wiener Haus', floor: 1, zone: 'OUTER', position: 12, type: 'Food e Ristoranti' },
    { id: 'p1_outer_13', name: 'Arabian Kebab', floor: 1, zone: 'OUTER', position: 13, type: 'Food e Ristoranti' },
    { id: 'p1_outer_wc_1', name: 'Bagno Sud P1', floor: 1, zone: 'OUTER', position: 14, type: 'Bagni' },
    { id: 'p1_outer_14', name: 'Alice Pizza Point', floor: 1, zone: 'OUTER', position: 15, type: 'Food e Ristoranti' },
    { id: 'p1_outer_15', name: 'Foodie', floor: 1, zone: 'OUTER', position: 16, type: 'Food e Ristoranti' },
    { id: 'p1_outer_16', name: 'Visionottica', floor: 1, zone: 'OUTER', position: 17, type: 'Salute e Bellezza' },
    { id: 'p1_outer_17', name: 'Cisalfa Sport', floor: 1, zone: 'OUTER', position: 18, type: 'Moda' },
    { id: 'p1_outer_18', name: 'Upim', floor: 1, zone: 'OUTER', position: 19, type: 'Moda' },
    { id: 'p1_outer_19', name: 'Ovs', floor: 1, zone: 'OUTER', position: 20, type: 'Moda' },
    { id: 'p1_outer_20', name: 'Unieuro', floor: 1, zone: 'OUTER', position: 21, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p1_outer_21', name: 'Skechers', floor: 1, zone: 'OUTER', position: 22, type: 'Moda' },
    { id: 'p1_outer_22', name: 'Prénatal', floor: 1, zone: 'OUTER', position: 23, type: 'Moda' },
    { id: 'p1_outer_23', name: 'Chicco', floor: 1, zone: 'OUTER', position: 24, type: 'Moda' },
    { id: 'p1_outer_24', name: 'Tommy Hilfiger', floor: 1, zone: 'OUTER', position: 25, type: 'Moda' },
    { id: 'p1_outer_25', name: 'Alviero Martini 1A Classe', floor: 1, zone: 'OUTER', position: 26, type: 'Moda' },
    { id: 'p1_outer_26', name: 'Fiorella Rubino', floor: 1, zone: 'OUTER', position: 27, type: 'Moda' },
    { id: 'p1_outer_27', name: 'Two Way', floor: 1, zone: 'OUTER', position: 28, type: 'Moda' },
    { id: 'p1_outer_28', name: 'Oltre', floor: 1, zone: 'OUTER', position: 29, type: 'Moda' },
    { id: 'p1_outer_29', name: 'The Bridge', floor: 1, zone: 'OUTER', position: 30, type: 'Moda' },
    { id: 'p1_outer_30', name: 'Toys con te', floor: 1, zone: 'OUTER', position: 31, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p1_outer_31', name: 'MediaWorld piano 1', floor: 1, zone: 'OUTER', position: 32, type: 'Prodotti per la casa' },
    { id: 'p1_outer_32', name: 'Zara Home', floor: 1, zone: 'OUTER', position: 33, type: 'Prodotti per la casa' },
    { id: 'p1_outer_33', name: 'Oysho', floor: 1, zone: 'OUTER', position: 34, type: 'Moda' },
    { id: 'p1_outer_34', name: 'Zara', floor: 1, zone: 'OUTER', position: 35, type: 'Moda' },
    { id: 'p1_outer_35', name: 'Desigual', floor: 1, zone: 'OUTER', position: 36, type: 'Moda' },
    { id: 'p1_outer_36', name: 'Max&Co.', floor: 1, zone: 'OUTER', position: 37, type: 'Moda' },
    { id: 'p1_outer_37', name: 'Luisa Spagnoli', floor: 1, zone: 'OUTER', position: 38, type: 'Moda' },
    { id: 'p1_outer_38', name: 'Pellizzari', floor: 1, zone: 'OUTER', position: 39, type: 'Moda' },
    { id: 'p1_outer_39', name: 'Guess', floor: 1, zone: 'OUTER', position: 40, type: 'Moda' },
    { id: 'p1_outer_40', name: 'Paul Taylor', floor: 1, zone: 'OUTER', position: 41, type: 'Moda' },
    { id: 'p1_outer_41', name: 'Mango', floor: 1, zone: 'OUTER', position: 42, type: 'Moda' },
    { id: 'p1_outer_42', name: 'Michael Kors', floor: 1, zone: 'OUTER', position: 43, type: 'Moda' },
    { id: 'p1_outer_43', name: 'Sephora', floor: 1, zone: 'OUTER', position: 44, type: 'Salute e Bellezza' },
    { id: 'p1_outer_44', name: 'Adidas', floor: 1, zone: 'OUTER', position: 45, type: 'Moda' },
    { id: 'p1_outer_45', name: 'Caffè Napoli', floor: 1, zone: 'OUTER', position: 46, type: 'Food e Ristoranti' },
    { id: 'p1_outer_46', name: 'Old Wild West', floor: 1, zone: 'OUTER', position: 47, type: 'Food e Ristoranti' },
    { id: 'p1_outer_47', name: 'Uci Cinemas', floor: 1, zone: 'OUTER', position: 48, type: 'Intrattenimento' },

    // Piano 1 - Isola Center (44 negozi)
    { id: 'p1_isl_ctr_1', name: 'Guess Accessories', floor: 1, zone: 'ISLAND_CENTER', position: 1, type: 'Moda' },
    { id: 'p1_isl_ctr_2', name: 'Dixie', floor: 1, zone: 'ISLAND_CENTER', position: 2, type: 'Moda' },
    { id: 'p1_isl_ctr_3', name: 'Solaris', floor: 1, zone: 'ISLAND_CENTER', position: 3, type: 'Salute e Bellezza' },
    { id: 'p1_isl_ctr_4', name: 'Nike', floor: 1, zone: 'ISLAND_CENTER', position: 4, type: 'Moda' },
    { id: 'p1_isl_ctr_5', name: 'New Balance', floor: 1, zone: 'ISLAND_CENTER', position: 5, type: 'Moda' },
    { id: 'p1_isl_ctr_6', name: 'Foot Locker', floor: 1, zone: 'ISLAND_CENTER', position: 6, type: 'Moda' },
    { id: 'p1_isl_ctr_7', name: 'Jack & Jones', floor: 1, zone: 'ISLAND_CENTER', position: 7, type: 'Moda' },
    { id: 'p1_isl_ctr_8', name: 'La Piadineria', floor: 1, zone: 'ISLAND_CENTER', position: 8, type: 'Food e Ristoranti' },
    { id: 'p1_isl_ctr_9', name: 'Grom', floor: 1, zone: 'ISLAND_CENTER', position: 9, type: 'Food e Ristoranti' },
    { id: 'p1_isl_ctr_10', name: 'Camicissima', floor: 1, zone: 'ISLAND_CENTER', position: 10, type: 'Moda' },
    { id: 'p1_isl_ctr_11', name: 'Legami', floor: 1, zone: 'ISLAND_CENTER', position: 11, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p1_isl_ctr_12', name: 'Dyson', floor: 1, zone: 'ISLAND_CENTER', position: 12, type: 'Prodotti per la casa' },
    { id: 'p1_isl_ctr_13', name: 'Primor', floor: 1, zone: 'ISLAND_CENTER', position: 13, type: 'Salute e Bellezza' },
    { id: 'p1_isl_ctr_14', name: 'Stroili', floor: 1, zone: 'ISLAND_CENTER', position: 14, type: 'Moda' },
    { id: 'p1_isl_ctr_15', name: 'Imperial', floor: 1, zone: 'ISLAND_CENTER', position: 15, type: 'Moda' },
    { id: 'p1_isl_ctr_16', name: 'GrandVision by Optissimo', floor: 1, zone: 'ISLAND_CENTER', position: 16, type: 'Salute e Bellezza' },
    { id: 'p1_isl_ctr_17', name: 'Funside', floor: 1, zone: 'ISLAND_CENTER', position: 17, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p1_isl_ctr_18', name: 'AS Roma', floor: 1, zone: 'ISLAND_CENTER', position: 18, type: 'Cultura, Regali, Tempo Libero' },
    { id: 'p1_isl_ctr_19', name: 'Sottotono', floor: 1, zone: 'ISLAND_CENTER', position: 19, type: 'Moda' },
    { id: 'p1_isl_ctr_20', name: 'Tim piano 1', floor: 1, zone: 'ISLAND_CENTER', position: 20, type: 'Servizi' },
    { id: 'p1_isl_ctr_21', name: 'Caporiccio', floor: 1, zone: 'ISLAND_CENTER', position: 21, type: 'Moda' },
    { id: 'p1_isl_ctr_22', name: 'Equivalenza', floor: 1, zone: 'ISLAND_CENTER', position: 22, type: 'Salute e Bellezza' },
    { id: 'p1_isl_ctr_23', name: "L'Erbolario", floor: 1, zone: 'ISLAND_CENTER', position: 23, type: 'Salute e Bellezza' },
    { id: 'p1_isl_ctr_24', name: 'Cotton&Silk', floor: 1, zone: 'ISLAND_CENTER', position: 24, type: 'Moda' },
    { id: 'p1_isl_ctr_25', name: 'Harmont & Blaine', floor: 1, zone: 'ISLAND_CENTER', position: 25, type: 'Moda' },
    { id: 'p1_isl_ctr_26', name: 'Calvin Klein Jeans', floor: 1, zone: 'ISLAND_CENTER', position: 26, type: 'Moda' },
    { id: 'p1_isl_ctr_27', name: 'The North Face', floor: 1, zone: 'ISLAND_CENTER', position: 27, type: 'Moda' },
    { id: 'p1_isl_ctr_28', name: 'Geox', floor: 1, zone: 'ISLAND_CENTER', position: 28, type: 'Moda' },
    { id: 'p1_isl_ctr_29', name: 'Timberland', floor: 1, zone: 'ISLAND_CENTER', position: 29, type: 'Moda' },
    { id: 'p1_isl_ctr_30', name: 'Melluso', floor: 1, zone: 'ISLAND_CENTER', position: 30, type: 'Moda' },
    { id: 'p1_isl_ctr_31', name: 'Gioielli di Valenza', floor: 1, zone: 'ISLAND_CENTER', position: 31, type: 'Moda' },
    { id: 'p1_isl_ctr_32', name: 'Dan John', floor: 1, zone: 'ISLAND_CENTER', position: 32, type: 'Moda' },
    { id: 'p1_isl_ctr_33', name: 'Noikika', floor: 1, zone: 'ISLAND_CENTER', position: 33, type: 'Moda' },
    { id: 'p1_isl_ctr_34', name: 'Pennyblack', floor: 1, zone: 'ISLAND_CENTER', position: 34, type: 'Moda' },
    { id: 'p1_isl_ctr_35', name: "Victoria's Secret", floor: 1, zone: 'ISLAND_CENTER', position: 35, type: 'Moda' },
    { id: 'p1_isl_ctr_36', name: 'Armani Exchange', floor: 1, zone: 'ISLAND_CENTER', position: 36, type: 'Moda' },
    { id: 'p1_isl_ctr_37', name: 'Stradivarius', floor: 1, zone: 'ISLAND_CENTER', position: 37, type: 'Moda' },
    { id: 'p1_isl_ctr_38', name: 'Coccinelle', floor: 1, zone: 'ISLAND_CENTER', position: 38, type: 'Moda' },
    { id: 'p1_isl_ctr_39', name: 'Lacoste', floor: 1, zone: 'ISLAND_CENTER', position: 39, type: 'Moda' },
    { id: 'p1_isl_ctr_40', name: 'Marella', floor: 1, zone: 'ISLAND_CENTER', position: 40, type: 'Moda' },
    { id: 'p1_isl_ctr_41', name: 'Camper', floor: 1, zone: 'ISLAND_CENTER', position: 41, type: 'Moda' },
    { id: 'p1_isl_ctr_42', name: 'David Naman', floor: 1, zone: 'ISLAND_CENTER', position: 42, type: 'Moda' },
    { id: 'p1_isl_ctr_43', name: 'Doppelganger piano 1', floor: 1, zone: 'ISLAND_CENTER', position: 43, type: 'Moda' },
    { id: 'p1_isl_ctr_44', name: 'Windtre (piano 1)', floor: 1, zone: 'ISLAND_CENTER', position: 44, type: 'Servizi' }
    ],
    
// Dati GranRoma
    'granroma': [
        // Piano 0 - Anello Esterno (25 negozi)
        { id: 'gr_p0_outer_1', name: "Deco'", floor: 0, zone: 'OUTER', position: 1, type: 'Supermercati' },
        { id: 'gr_p0_outer_2', name: 'Cisalfa Sport', floor: 0, zone: 'OUTER', position: 2, type: 'Moda' },
        { id: 'gr_p0_outer_3', name: 'Dentalpro', floor: 0, zone: 'OUTER', position: 3, type: 'Salute e Bellezza' },
        { id: 'gr_p0_outer_4', name: 'La Casina Del Caffe', floor: 0, zone: 'OUTER', position: 4, type: 'Food e Ristoranti' },
        { id: 'gr_p0_outer_5', name: 'Kasanova+', floor: 0, zone: 'OUTER', position: 5, type: 'Prodotti per la casa' },
        { id: 'gr_p0_outer_wc_1', name: 'Bagno P0', floor: 0, zone: 'OUTER', position: 6, type: 'Bagni' },
        { id: 'gr_p0_outer_6', name: 'Mayoral', floor: 0, zone: 'OUTER', position: 7, type: 'Moda' },
        { id: 'gr_p0_outer_7', name: 'Mango', floor: 0, zone: 'OUTER', position: 8, type: 'Moda' },
        { id: 'gr_p0_outer_8', name: 'Nuvolari', floor: 0, zone: 'OUTER', position: 9, type: 'Moda' },
        { id: 'gr_p0_outer_9', name: 'Flying Tiger Copenhagen', floor: 0, zone: 'OUTER', position: 10, type: 'Cultura, Regali, Tempo Libero' },
        { id: 'gr_p0_outer_10', name: 'Gelateria Cremilla', floor: 0, zone: 'OUTER', position: 11, type: 'Food e Ristoranti' },
        { id: 'gr_p0_outer_11', name: 'Jdsports', floor: 0, zone: 'OUTER', position: 12, type: 'Moda' },
        { id: 'gr_p0_outer_12', name: 'Zara', floor: 0, zone: 'OUTER', position: 13, type: 'Moda' },
        { id: 'gr_p0_outer_13', name: 'Tramas', floor: 0, zone: 'OUTER', position: 14, type: 'Moda' },
        { id: 'gr_p0_outer_14', name: 'Amorestore', floor: 0, zone: 'OUTER', position: 15, type: 'Moda' },
        { id: 'gr_p0_outer_15', name: 'Tezenis', floor: 0, zone: 'OUTER', position: 16, type: 'Moda' },
        { id: 'gr_p0_outer_16', name: 'Ovs', floor: 0, zone: 'OUTER', position: 17, type: 'Moda' },
        { id: 'gr_p0_outer_17', name: 'Punt Roma', floor: 0, zone: 'OUTER', position: 18, type: 'Moda' },
        { id: 'gr_p0_outer_18', name: 'Legami Milano', floor: 0, zone: 'OUTER', position: 19, type: 'Moda' },
        { id: 'gr_p0_outer_19', name: 'Sorbino', floor: 0, zone: 'OUTER', position: 20, type: 'Moda' },
        { id: 'gr_p0_outer_20', name: 'Primadonna Collection', floor: 0, zone: 'OUTER', position: 21, type: 'Moda' },
        { id: 'gr_p0_outer_21', name: 'Yvesrocher', floor: 0, zone: 'OUTER', position: 22, type: 'Salute e Bellezza' },
        { id: 'gr_p0_outer_22', name: 'Cex', floor: 0, zone: 'OUTER', position: 23, type: 'Cultura, Regali, Tempo Libero' },
        { id: 'gr_p0_outer_23', name: 'Èqui', floor: 0, zone: 'OUTER', position: 24, type: 'Salute e Bellezza' },
        { id: 'gr_p0_outer_24', name: 'Skechers', floor: 0, zone: 'OUTER', position: 25, type: 'Moda' },
        { id: 'gr_p0_outer_25', name: 'Douglas', floor: 0, zone: 'OUTER', position: 26, type: 'Salute e Bellezza' },
        { id: 'gr_p0_outer_26', name: 'Maisons Du Monde', floor: 0, zone: 'OUTER', position: 27, type: 'Prodotti per la casa' },


        // Piano 0 - Isola Centrale (21 negozi)
        { id: 'gr_p0_isl_1', name: 'Stroili', floor: 0, zone: 'ISLAND_CENTER', position: 1, type: 'Moda' },
        { id: 'gr_p0_isl_2', name: 'Carpisa', floor: 0, zone: 'ISLAND_CENTER', position: 2, type: 'Moda' },
        { id: 'gr_p0_isl_3', name: 'Lama Optical', floor: 0, zone: 'ISLAND_CENTER', position: 3, type: 'Salute e Bellezza' },
        { id: 'gr_p0_isl_4', name: 'Zuiki', floor: 0, zone: 'ISLAND_CENTER', position: 4, type: 'Moda' },
        { id: 'gr_p0_isl_5', name: 'Parfois', floor: 0, zone: 'ISLAND_CENTER', position: 5, type: 'Moda' },
        { id: 'gr_p0_isl_6', name: 'Bluespirit Ingresso', floor: 0, zone: 'ISLAND_CENTER', position: 6, type: 'Moda' },
        { id: 'gr_p0_isl_7', name: 'Mondovista', floor: 0, zone: 'ISLAND_CENTER', position: 7, type: 'Salute e Bellezza' },
        { id: 'gr_p0_isl_8', name: 'Omai', floor: 0, zone: 'ISLAND_CENTER', position: 8, type: 'Moda' },
        { id: 'gr_p0_isl_9', name: 'Talco', floor: 0, zone: 'ISLAND_CENTER', position: 9, type: 'Moda' },
        { id: 'gr_p0_isl_10', name: 'Kamalion', floor: 0, zone: 'ISLAND_CENTER', position: 10, type: 'Moda' },
        { id: 'gr_p0_isl_11', name: 'Grandvision', floor: 0, zone: 'ISLAND_CENTER', position: 11, type: 'Salute e Bellezza' },
        { id: 'gr_p0_isl_12', name: 'Calzedonia', floor: 0, zone: 'ISLAND_CENTER', position: 12, type: 'Moda' },
        { id: 'gr_p0_isl_13', name: 'Bluespirit', floor: 0, zone: 'ISLAND_CENTER', position: 13, type: 'Moda' },
        //{ id: 'gr_p0_isl_14', name: 'Satur', floor: 0, zone: 'ISLAND_CENTER', position: 14, type: 'Prodotti per la casa' },
        //{ id: 'gr_p0_isl_15', name: 'Bata', floor: 0, zone: 'ISLAND_CENTER', position: 15, type: 'Moda' },
        { id: 'gr_p0_isl_17', name: 'Intimissimi', floor: 0, zone: 'ISLAND_CENTER', position: 17, type: 'Moda' },
        { id: 'gr_p0_isl_18', name: 'Vodafone', floor: 0, zone: 'ISLAND_CENTER', position: 18, type: 'Servizi' },
        { id: 'gr_p0_isl_19', name: 'Originalmarines', floor: 0, zone: 'ISLAND_CENTER', position: 19, type: 'Moda' },
        { id: 'gr_p0_isl_20', name: 'Medimarket', floor: 0, zone: 'ISLAND_CENTER', position: 20, type: 'Salute e Bellezza' },
        { id: 'gr_p0_isl_21', name: 'Snipes', floor: 0, zone: 'ISLAND_CENTER', position: 21, type: 'Moda' },


        // Piano 1 - Anello Esterno (21 negozi)
        { id: 'gr_p1_outer_1', name: 'Burger King', floor: 1, zone: 'OUTER', position: 1, type: 'Food e Ristoranti' },
        { id: 'gr_p1_outer_2', name: "Hamerica's", floor: 1, zone: 'OUTER', position: 2, type: 'Food e Ristoranti' },
        { id: 'gr_p1_outer_wc_1', name: 'Bagno P1', floor: 1, zone: 'OUTER', position: 3, type: 'Bagni' },
        { id: 'gr_p1_outer_3', name: 'Kitikate', floor: 1, zone: 'OUTER', position: 4, type: 'Moda' },
        { id: 'gr_p1_outer_4', name: 'Mister Games', floor: 1, zone: 'OUTER', position: 5, type: 'Intrattenimento' },
        { id: 'gr_p1_outer_5', name: 'Estasi Profumerie', floor: 1, zone: 'OUTER', position: 6, type: 'Salute e Bellezza' },
        { id: 'gr_p1_outer_6', name: 'Odstore', floor: 1, zone: 'OUTER', position: 7, type: 'Food e Ristoranti' },
        { id: 'gr_p1_outer_7', name: 'Jack & Jones', floor: 1, zone: 'OUTER', position: 8, type: 'Moda' },
        { id: 'gr_p1_outer_8', name: 'Stradivarius', floor: 1, zone: 'OUTER', position: 9, type: 'Moda' },
        { id: 'gr_p1_outer_9', name: 'Zara Piano 1', floor: 1, zone: 'OUTER', position: 10, type: 'Moda' },
        { id: 'gr_p1_outer_10', name: 'Muy Mucho', floor: 1, zone: 'OUTER', position: 11, type: 'Prodotti per la casa' },
        { id: 'gr_p1_outer_11', name: 'Pull & Bear', floor: 1, zone: 'OUTER', position: 12, type: 'Moda' },
        { id: 'gr_p1_outer_12', name: 'Action', floor: 1, zone: 'OUTER', position: 13, type: 'Prodotti per la casa' },
        { id: 'gr_p1_outer_13', name: 'Bershka', floor: 1, zone: 'OUTER', position: 14, type: 'Moda' },
        { id: 'gr_p1_outer_14', name: 'Pepco', floor: 1, zone: 'OUTER', position: 15, type: 'Prodotti per la casa' },
        { id: 'gr_p1_outer_15', name: 'Live978', floor: 1, zone: 'OUTER', position: 16, type: 'Cultura, Regali, Tempo Libero' },
        { id: 'gr_p1_outer_16', name: 'Mediaworld', floor: 1, zone: 'OUTER', position: 17, type: 'Cultura, Regali, Tempo Libero' },
        { id: 'gr_p1_outer_17', name: "Villabebe'", floor: 1, zone: 'OUTER', position: 18, type: 'Moda' },
        { id: 'gr_p1_outer_18', name: 'Billy Tacos', floor: 1, zone: 'OUTER', position: 19, type: 'Food e Ristoranti' },
        { id: 'gr_p1_outer_19', name: 'La Piadineria', floor: 1, zone: 'OUTER', position: 20, type: 'Food e Ristoranti' },
        { id: 'gr_p1_outer_20', name: 'Roadhouse Restaurant', floor: 1, zone: 'OUTER', position: 21, type: 'Food e Ristoranti' },
        { id: 'gr_p1_outer_21', name: 'Fantasie Di Napoli', floor: 1, zone: 'OUTER', position: 22, type: 'Food e Ristoranti' },


        // Piano 1 - Isola Centrale (19 negozi)
        { id: 'gr_p1_isl_1', name: 'Caffè Vergnano 1882', floor: 1, zone: 'ISLAND_CENTER', position: 1, type: 'Food e Ristoranti' },
        { id: 'gr_p1_isl_2', name: 'Tabaccheria', floor: 1, zone: 'ISLAND_CENTER', position: 2, type: 'Servizi' },
        { id: 'gr_p1_isl_3', name: 'Queen Helena', floor: 1, zone: 'ISLAND_CENTER', position: 3, type: 'Moda' },
        { id: 'gr_p1_isl_4', name: 'Rinascimento', floor: 1, zone: 'ISLAND_CENTER', position: 4, type: 'Moda' },
        { id: 'gr_p1_isl_5', name: 'Sartoria Italiana', floor: 1, zone: 'ISLAND_CENTER', position: 5, type: 'Moda' },
        { id: 'gr_p1_isl_6', name: 'Pink Gioielli', floor: 1, zone: 'ISLAND_CENTER', position: 6, type: 'Moda' },
        { id: 'gr_p1_isl_7', name: 'Brend Atelier', floor: 1, zone: 'ISLAND_CENTER', position: 7, type: 'Moda' },
        { id: 'gr_p1_isl_8', name: 'Dan Jhon', floor: 1, zone: 'ISLAND_CENTER', position: 8, type: 'Moda' },
        { id: 'gr_p1_isl_9', name: 'Guess', floor: 1, zone: 'ISLAND_CENTER', position: 9, type: 'Moda' },
        { id: 'gr_p1_isl_10', name: "D'S Damat", floor: 1, zone: 'ISLAND_CENTER', position: 10, type: 'Moda' },
        { id: 'gr_p1_isl_11', name: 'Dly', floor: 1, zone: 'ISLAND_CENTER', position: 11, type: 'Moda' },
        { id: 'gr_p1_isl_12', name: 'Dverso', floor: 1, zone: 'ISLAND_CENTER', position: 12, type: 'Moda' },
        { id: 'gr_p1_isl_13', name: 'Gioiellivalenza', floor: 1, zone: 'ISLAND_CENTER', position: 13, type: 'Moda' },
        { id: 'gr_p1_isl_14', name: 'Wind Tre', floor: 1, zone: 'ISLAND_CENTER', position: 14, type: 'Servizi' },
        { id: 'gr_p1_isl_15', name: 'Findomestic', floor: 1, zone: 'ISLAND_CENTER', position: 15, type: 'Servizi' },
        { id: 'gr_p1_isl_16', name: 'Marlù', floor: 1, zone: 'ISLAND_CENTER', position: 16, type: 'Moda' },
        { id: 'gr_p1_isl_17', name: 'Giunti Al Punto', floor: 1, zone: 'ISLAND_CENTER', position: 17, type: 'Cultura, Regali, Tempo Libero' },
        { id: 'gr_p1_isl_18', name: 'Machapokè', floor: 1, zone: 'ISLAND_CENTER', position: 18, type: 'Food e Ristoranti' },
        { id: 'gr_p1_isl_19', name: 'Minipizza 22C M2', floor: 1, zone: 'ISLAND_CENTER', position: 19, type: 'Food e Ristoranti' },


        // Piano 1 - Mini Isole (3 negozi separati)
        { id: 'gr_p1_mini_1', name: 'I Baccanali', floor: 1, zone: 'ISLAND_MINI', position: 1, type: 'Food e Ristoranti' },
        { id: 'gr_p1_mini_2', name: 'Capatoast Toasteria', floor: 1, zone: 'ISLAND_MINI', position: 2, type: 'Food e Ristoranti' },
        { id: 'gr_p1_mini_3', name: 'Equivalenza', floor: 1, zone: 'ISLAND_MINI', position: 3, type: 'Salute e Bellezza' }
    ]
};

// Variabile globale per il mall selezionato
let selectedMall = null;
let SHOPS_DATA = [];
